language: node_js
node_js:
- '0.10'
env:
  global:
  - SAUCE_USERNAME: michaelweibel
  - CANDY_VAGRANT: false
  - secure: "e32tnzC3ZRA7CTqek48Xm5rfUczBExV0UW+2nrkLGoiV548+Ui0YlERcbkdmlby4RIzjVf9sKRlgMyYnmD/MvE6VVumX0nEDGJN21Ojxf/xWCPavdX1nU+zGHxE5AUl8dReOWXtvpkxuJRy3rNsvNUaLc8sGkK+5eQhA3KBTO8o="
before_script:
- npm install -g grunt-cli bower
- npm install
- bower install
