language: node_js
node_js:
- '0.10'
env:
  global:
  - SAUCE_USERNAME: candy-chat-ci
  - CANDY_VAGRANT: false
  - secure: j3WtBCNS0sF73F/5yjw2O4XHus7HdeQT1AfUxaEt9+lX5v8IUKu4y/kUHE7bGjFC+eb8zsh+R49oZm9RFTwtTrfl+Chiz9h9I6S++ofXX8G/UKJgYXPVY98qrcHeIhWpm1N3G1B4/yxHN8NtzVmWK+Tg/LxX+75gnNxaoLR4Zgo=
before_script:
- npm install -g grunt-cli bower
- npm install
- bower install
